package temperatureconversion;

import javax.swing.JOptionPane;

/**
 * This is the graphical user interface for this program
 * @author Chris Gonzalez Version 1.0 11/08/2016 
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        txtTemperatureToBeConverted = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        lblConvertedTemperature = new javax.swing.JLabel();
        btnConvertTemperature = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        rbFahrenheitToCelsius = new javax.swing.JRadioButton();
        rbCelsiusToFahrenheit = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Temperature Conversion");
        setAlwaysOnTop(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Temperature value to be converted:");

        txtTemperatureToBeConverted.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTemperatureToBeConvertedActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("° ");

        lblConvertedTemperature.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblConvertedTemperature.setText("x");

        btnConvertTemperature.setText("Convert");
        btnConvertTemperature.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConvertTemperatureActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Choose Conversion"));

        buttonGroup1.add(rbFahrenheitToCelsius);
        rbFahrenheitToCelsius.setSelected(true);
        rbFahrenheitToCelsius.setText("Fahrenheit to Celsius");

        buttonGroup1.add(rbCelsiusToFahrenheit);
        rbCelsiusToFahrenheit.setText("Celsius to Fahrenheit");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbFahrenheitToCelsius)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rbCelsiusToFahrenheit)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbFahrenheitToCelsius)
                    .addComponent(rbCelsiusToFahrenheit)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblConvertedTemperature)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnConvertTemperature))
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtTemperatureToBeConverted, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtTemperatureToBeConverted, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblConvertedTemperature)
                        .addComponent(jLabel2))
                    .addComponent(btnConvertTemperature))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConvertTemperatureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConvertTemperatureActionPerformed
        try{
            TemperatureConverterStrategy fahrenheitToCelsius = 
                new FahrenheitToCelsiusConverter();
            TemperatureConverterStrategy celsiusToFahrenheit = 
                new CelsiusToFahrenheitConverter();
            TemperatureConversionManager temperatureConversion = 
                new TemperatureConversionManager();
            if(rbCelsiusToFahrenheit.isSelected()){    
                lblConvertedTemperature.setText(temperatureConversion
                        .getConvertedTemperature(Double
                        .parseDouble(txtTemperatureToBeConverted
                        .getText()),celsiusToFahrenheit));
            }
            if(rbFahrenheitToCelsius.isSelected()){
                lblConvertedTemperature.setText(temperatureConversion
                        .getConvertedTemperature(Double
                        .parseDouble(txtTemperatureToBeConverted
                        .getText()),fahrenheitToCelsius));
            }
        }catch(NumberFormatException nf){
            JOptionPane.showMessageDialog(rootPane, "Please enter a valid value");
        }catch(IllegalArgumentException ia){
            JOptionPane.showMessageDialog(rootPane, ia.getMessage());
        }
    }//GEN-LAST:event_btnConvertTemperatureActionPerformed

    private void txtTemperatureToBeConvertedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTemperatureToBeConvertedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTemperatureToBeConvertedActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConvertTemperature;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblConvertedTemperature;
    private javax.swing.JRadioButton rbCelsiusToFahrenheit;
    private javax.swing.JRadioButton rbFahrenheitToCelsius;
    private javax.swing.JTextField txtTemperatureToBeConverted;
    // End of variables declaration//GEN-END:variables
}
